In [23]:
import pandas as pd
import optuna
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import TensorDataset, DataLoader
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error
import os
import shutil
from huggingface_hub import hf_hub_download

# Dataset & Preprocessing

In [2]:
data_path = 'dataset_model/dataset_trainable_rev2.csv'

In [3]:
if os.path.exists(data_path):
    print(f"Dataset Raw lokal sudah ada di '{data_path}'.")
else:
    print(f"Dataset Raw lokal belum ada. Mengunduh dataset dari Hugging Face...")
    
    temp_downloaded_path = hf_hub_download(
        repo_id="vel740/dhaka-smart-waste-processed",
        filename="processed/dataset_trainable_rev2.csv",
        repo_type="dataset"
    )
    
    os.makedirs('dataset_model', exist_ok=True)
    shutil.copy(temp_downloaded_path, data_path)
    print(f"Dataset selesai diunduh dan tersimpan di '{data_path}'.")

df = pd.read_csv(data_path)
print(f"Total baris awal: {len(df):,} baris")

Dataset Raw lokal sudah ada di 'dataset_model/dataset_trainable_rev2.csv'.
Total baris awal: 15,650 baris

In [4]:
# Hitung selisih target dan lag ke-3 untuk mendeteksi event pickup (> 20% drop)
target_diff = df['target_next_hour'] - df['fill_level_percent']
velocity_3h = df['lag_2h'] - df['lag_3h']

# Hanya ambil fase akumulasi murni (bebas dari drop pengangkutan sampah)
clean_mask = (
    (target_diff > -20.0) & 
    (df['velocity_1h'] > -20.0) & 
    (df['velocity_2h'] > -20.0) & 
    (velocity_3h > -20.0)
)

df_clean = df[clean_mask].reset_index(drop=True)
print(f"Total baris setelah pembersihan event pickup: {len(df_clean):,} baris (Dibuang: {len(df) - len(df_clean)} baris)")

Total baris setelah pembersihan event pickup: 15,650 baris (Dibuang: 0 baris)

In [5]:
df.head(5)

,bin_index,timestamp_unix,fill_level_percent,lag_1h,lag_2h,lag_3h,lag_24h,lag_48h,is_weekend,velocity_1h,velocity_2h,hour_sin,hour_cos,day_sin,day_cos,target_next_hour
0,0,1735840800,67.709990,68.51879,66.02875,67.10285,42.061382,14.483168,0,-0.808800,2.490044,0.000000,1.000000,-0.433884,-0.900969,70.403190
1,0,1735844400,70.403190,67.70999,68.51879,66.02875,42.492905,15.378024,0,2.693199,-0.808800,0.258819,0.965926,-0.433884,-0.900969,69.584000
2,0,1735848000,69.584000,70.40319,67.70999,68.51879,44.316532,16.866007,0,-0.819191,2.693199,0.500000,0.866025,-0.433884,-0.900969,72.692300
3,0,1735851600,72.692300,69.58400,70.40319,67.70999,43.484684,18.462954,0,3.108299,-0.819191,0.707107,0.707107,-0.433884,-0.900969,68.450325
4,0,1735855200,68.450325,72.69230,69.58400,70.40319,44.515327,20.921236,0,-4.241974,3.108299,0.866025,0.500000,-0.433884,-0.900969,72.475070

In [6]:
df_clean.head(5)

,bin_index,timestamp_unix,fill_level_percent,lag_1h,lag_2h,lag_3h,lag_24h,lag_48h,is_weekend,velocity_1h,velocity_2h,hour_sin,hour_cos,day_sin,day_cos,target_next_hour
0,0,1735840800,67.709990,68.51879,66.02875,67.10285,42.061382,14.483168,0,-0.808800,2.490044,0.000000,1.000000,-0.433884,-0.900969,70.403190
1,0,1735844400,70.403190,67.70999,68.51879,66.02875,42.492905,15.378024,0,2.693199,-0.808800,0.258819,0.965926,-0.433884,-0.900969,69.584000
2,0,1735848000,69.584000,70.40319,67.70999,68.51879,44.316532,16.866007,0,-0.819191,2.693199,0.500000,0.866025,-0.433884,-0.900969,72.692300
3,0,1735851600,72.692300,69.58400,70.40319,67.70999,43.484684,18.462954,0,3.108299,-0.819191,0.707107,0.707107,-0.433884,-0.900969,68.450325
4,0,1735855200,68.450325,72.69230,69.58400,70.40319,44.515327,20.921236,0,-4.241974,3.108299,0.866025,0.500000,-0.433884,-0.900969,72.475070

In [7]:
features = [
    'fill_level_percent', 'lag_1h', 'lag_2h', 'lag_3h', 
    'lag_24h', 'lag_48h', 'is_weekend',
    'velocity_1h', 'velocity_2h', 
    'hour_sin', 'hour_cos', 'day_sin', 'day_cos'
]
target = 'target_next_hour'

# Temporal Split
split_timestamp = df_clean['timestamp_unix'].quantile(0.8)
train_mask = df_clean['timestamp_unix'] <= split_timestamp
test_mask = df_clean['timestamp_unix'] > split_timestamp

X_train_raw = df_clean.loc[train_mask, features].values
y_train_raw = df_clean.loc[train_mask, target].values
X_test_raw = df_clean.loc[test_mask, features].values
y_test_raw = df_clean.loc[test_mask, target].values

In [8]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_raw)
X_test_scaled = scaler.transform(X_test_raw)

In [9]:
def create_sequences(X, y, seq_length):
    xs, ys = [], []
    for i in range(len(X) - seq_length):
        xs.append(X[i:(i + seq_length)])
        ys.append(y[i + seq_length])
    return np.array(xs), np.array(ys)

SEQUENCE_LENGTH = 12 # Looking at the past 12 hours to predict the 13th
X_train_seq, y_train_seq = create_sequences(X_train_scaled, y_train_raw, SEQUENCE_LENGTH)
X_test_seq, y_test_seq = create_sequences(X_test_scaled, y_test_raw, SEQUENCE_LENGTH)

In [10]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Training on device: {device}")

train_dataset = TensorDataset(torch.tensor(X_train_seq, dtype=torch.float32), 
                              torch.tensor(y_train_seq, dtype=torch.float32))
test_dataset = TensorDataset(torch.tensor(X_test_seq, dtype=torch.float32), 
                             torch.tensor(y_test_seq, dtype=torch.float32))

Training on device: cuda

In [11]:
train_loader = DataLoader(train_dataset, batch_size=64, shuffle=False) 
test_loader = DataLoader(test_dataset, batch_size=64, shuffle=False)

# Baseline Model

In [12]:
class SmartBinLSTM(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers, output_size):
        super(SmartBinLSTM, self).__init__()
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        
        # batch_first=True ensures input format is (Batch, Sequence, Features)
        self.lstm = nn.LSTM(input_size, hidden_size, num_layers, batch_first=True)
        self.fc = nn.Linear(hidden_size, output_size)

    def forward(self, x):
        h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(device)
        c0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(device)
        
        out, _ = self.lstm(x, (h0, c0))
        out = self.fc(out[:, -1, :]) 
        return out.squeeze() # Squeeze removes unnecessary dimensions

In [13]:
model = SmartBinLSTM(input_size=len(features), hidden_size=32, num_layers=1, output_size=1).to(device)
criterion = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.005)

EPOCHS = 50

print("\n=== STARTING PYTORCH LSTM TRAINING ===")
for epoch in range(EPOCHS):
    model.train()
    train_losses = []
    
    for X_batch, y_batch in train_loader:
        X_batch, y_batch = X_batch.to(device), y_batch.to(device)
        
        optimizer.zero_grad()         # Clear old gradients
        predictions = model(X_batch)  # Forward pass
        loss = criterion(predictions, y_batch)
        
        loss.backward()               # Backpropagation
        optimizer.step()              # Update weights
        
        train_losses.append(loss.item())
        
    if (epoch + 1) % 10 == 0:
        print(f"Epoch [{epoch+1}/{EPOCHS}] - MSE Loss: {np.mean(train_losses):.4f}")

=== STARTING PYTORCH LSTM TRAINING ===
Epoch [10/50] - MSE Loss: 61.8358
Epoch [20/50] - MSE Loss: 59.3891
Epoch [30/50] - MSE Loss: 58.1465
Epoch [40/50] - MSE Loss: 56.1833
Epoch [50/50] - MSE Loss: 54.7104

In [14]:
model.eval()
all_preds = []
all_targets = []

In [15]:
with torch.no_grad(): # Disable gradient calculation for faster evaluation
    for X_batch, y_batch in test_loader:
        X_batch = X_batch.to(device)
        preds = model(X_batch).cpu().numpy()
        all_preds.extend(preds)
        all_targets.extend(y_batch.numpy())

all_preds = np.array(all_preds)
all_targets = np.array(all_targets)

final_mae = mean_absolute_error(all_targets, all_preds)
final_rmse = np.sqrt(mean_squared_error(all_targets, all_preds))

print("\n=== HASIL EVALUASI BASELINE LSTM ===")
print(f"Overall MAE (Semua Kondisi): {final_mae:.4f}%")
print(f"Overall RMSE               : {final_rmse:.4f}%")
print(f"LightGBM MAE Baseline      : 1.6079%")
print(f"Difference                 : {final_mae - 1.6079:+.4f}%")

=== HASIL EVALUASI BASELINE LSTM ===
Overall MAE (Semua Kondisi): 3.8451%
Overall RMSE               : 8.7608%
LightGBM MAE Baseline      : 1.6079%
Difference                 : +2.2372%

# Model Tuning

In [24]:
class SmartBinLSTM(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers, output_size, dropout_rate):
        super(SmartBinLSTM, self).__init__()
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        
        # PyTorch requires num_layers > 1 to apply internal LSTM dropout
        lstm_drop = dropout_rate if num_layers > 1 else 0.0
        
        self.lstm = nn.LSTM(input_size, hidden_size, num_layers, 
                            batch_first=True, dropout=lstm_drop)
        self.fc = nn.Linear(hidden_size, output_size)

    def forward(self, x):
        h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(x.device)
        c0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(x.device)
        
        out, _ = self.lstm(x, (h0, c0))
        out = self.fc(out[:, -1, :]) 
        return out.squeeze()

In [25]:
def objective(trial):
    # --- Define Hyperparameters for this trial ---
    seq_length = trial.suggest_int('seq_length', 3, 12)
    hidden_size = trial.suggest_categorical('hidden_size', [16, 32, 64, 128])
    num_layers = trial.suggest_int('num_layers', 1, 3)
    dropout_rate = trial.suggest_float('dropout_rate', 0.1, 0.5)
    lr = trial.suggest_float('learning_rate', 1e-4, 1e-2, log=True)
    batch_size = trial.suggest_categorical('batch_size', [32, 64, 128])
    
    # --- Dynamically rebuild 3D Tensors based on seq_length ---
    X_tr_seq, y_tr_seq = create_sequences(X_train_scaled, y_train_raw, seq_length)
    X_te_seq, y_te_seq = create_sequences(X_test_scaled, y_test_raw, seq_length)
    
    train_dataset = TensorDataset(torch.tensor(X_tr_seq, dtype=torch.float32), 
                                  torch.tensor(y_tr_seq, dtype=torch.float32))
    test_dataset = TensorDataset(torch.tensor(X_te_seq, dtype=torch.float32), 
                                 torch.tensor(y_te_seq, dtype=torch.float32))
    
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=False)
    test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)
    
    # --- Initialize Model ---
    model = SmartBinLSTM(len(features), hidden_size, num_layers, 1, dropout_rate).to(device)
    criterion = nn.MSELoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    
    # --- Fast Training Loop (30 Epochs per trial for speed) ---
    EPOCHS = 30
    model.train()
    for epoch in range(EPOCHS):
        for X_batch, y_batch in train_loader:
            X_batch, y_batch = X_batch.to(device), y_batch.to(device)
            optimizer.zero_grad()
            preds = model(X_batch)
            loss = criterion(preds, y_batch)
            loss.backward()
            optimizer.step()
            
    # --- Evaluation ---
    model.eval()
    all_preds, all_targets = [], []
    with torch.no_grad():
        for X_batch, y_batch in test_loader:
            X_batch = X_batch.to(device)
            preds = model(X_batch).cpu().numpy()
            all_preds.extend(preds)
            all_targets.extend(y_batch.numpy())
            
    # Optuna will attempt to minimize this MAE
    return mean_absolute_error(all_targets, all_preds)

In [26]:
study_name = "pytorch_lstm_smartbin_v1"
db_filename = "sqlite:///optuna_smartbin_study.sqlite3"

study = optuna.create_study(
    study_name=study_name,
    storage=db_filename,
    direction='minimize',
    load_if_exists=True
)

print(f"Starting GPU Optuna Tuning on {device}...")
# Running 50 trials. With your 5070 Ti, this should take less than 15 minutes.
study.optimize(objective, n_trials=50, show_progress_bar=True)

print("\n=== OPTUNA LSTM TUNING COMPLETE ===")
print(f"Best Validation MAE: {study.best_value:.4f}%")
print("Best Parameters:", study.best_params)

[I 2026-11-01 20:21:57,908] A new study created in RDB with name: pytorch_lstm_smartbin_v1

Starting GPU Optuna Tuning on cuda...

Best trial: 0. Best value: 31.6388:   2%|▏         | 1/50 [00:07<05:59,  7.33s/it]

[I 2026-11-01 20:22:05,236] Trial 0 finished with value: 31.638797151017513 and parameters: {'seq_length': 7, 'hidden_size': 16, 'num_layers': 3, 'dropout_rate': 0.18907426851916692, 'learning_rate': 0.00016039772271470566, 'batch_size': 128}. Best is trial 0 with value: 31.638797151017513.

Best trial: 1. Best value: 22.7381:   4%|▍         | 2/50 [00:14<05:39,  7.07s/it]

[I 2026-11-01 20:22:12,115] Trial 1 finished with value: 22.738086672766556 and parameters: {'seq_length': 8, 'hidden_size': 16, 'num_layers': 3, 'dropout_rate': 0.29243464774230554, 'learning_rate': 0.0005080192140120148, 'batch_size': 128}. Best is trial 1 with value: 22.738086672766556.

Best trial: 2. Best value: 4.15658:   6%|▌         | 3/50 [00:37<11:29, 14.67s/it]

[I 2026-11-01 20:22:35,828] Trial 2 finished with value: 4.156575807938684 and parameters: {'seq_length': 11, 'hidden_size': 32, 'num_layers': 3, 'dropout_rate': 0.33342249547418445, 'learning_rate': 0.006194366129449667, 'batch_size': 32}. Best is trial 2 with value: 4.156575807938684.

c:\Users\ardel\.conda\envs\pytorch_gpu_env\lib\site-packages\torch\nn\modules\loss.py:626: UserWarning: Using a target size (torch.Size([1])) that is different to the input size (torch.Size([])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
Best trial: 3. Best value: 3.88272:   8%|▊         | 4/50 [00:48<10:08, 13.22s/it]

[I 2026-11-01 20:22:46,831] Trial 3 finished with value: 3.8827161232348137 and parameters: {'seq_length': 4, 'hidden_size': 32, 'num_layers': 2, 'dropout_rate': 0.45768846619054016, 'learning_rate': 0.007672046718700507, 'batch_size': 64}. Best is trial 3 with value: 3.8827161232348137.

Best trial: 3. Best value: 3.88272:  10%|█         | 5/50 [00:59<09:05, 12.11s/it]

[I 2026-11-01 20:22:56,976] Trial 4 finished with value: 4.010012129666003 and parameters: {'seq_length': 12, 'hidden_size': 64, 'num_layers': 2, 'dropout_rate': 0.4459177615619302, 'learning_rate': 0.005397642615874477, 'batch_size': 64}. Best is trial 3 with value: 3.8827161232348137.

Best trial: 3. Best value: 3.88272:  12%|█▏        | 6/50 [01:04<07:11,  9.81s/it]

[I 2026-11-01 20:23:02,306] Trial 5 finished with value: 4.020575212030756 and parameters: {'seq_length': 5, 'hidden_size': 128, 'num_layers': 1, 'dropout_rate': 0.45337809092641035, 'learning_rate': 0.0010153055060238554, 'batch_size': 128}. Best is trial 3 with value: 3.8827161232348137.

Best trial: 3. Best value: 3.88272:  14%|█▍        | 7/50 [01:13<06:57,  9.70s/it]

[I 2026-11-01 20:23:11,790] Trial 6 finished with value: 3.981467583849761 and parameters: {'seq_length': 10, 'hidden_size': 128, 'num_layers': 1, 'dropout_rate': 0.351115032736784, 'learning_rate': 0.000931966747744534, 'batch_size': 64}. Best is trial 3 with value: 3.8827161232348137.

Best trial: 3. Best value: 3.88272:  16%|█▌        | 8/50 [01:28<07:52, 11.24s/it]

[I 2026-11-01 20:23:26,332] Trial 7 finished with value: 4.091818654437154 and parameters: {'seq_length': 3, 'hidden_size': 32, 'num_layers': 3, 'dropout_rate': 0.1146268428676701, 'learning_rate': 0.0028235097663719916, 'batch_size': 64}. Best is trial 3 with value: 3.8827161232348137.

Best trial: 3. Best value: 3.88272:  18%|█▊        | 9/50 [01:49<09:48, 14.35s/it]

[I 2026-11-01 20:23:47,511] Trial 8 finished with value: 4.2505298803666856 and parameters: {'seq_length': 3, 'hidden_size': 16, 'num_layers': 1, 'dropout_rate': 0.29788618510826914, 'learning_rate': 0.0006858424195509049, 'batch_size': 32}. Best is trial 3 with value: 3.8827161232348137.

Best trial: 3. Best value: 3.88272:  20%|██        | 10/50 [02:19<12:49, 19.23s/it]

[I 2026-11-01 20:24:17,664] Trial 9 finished with value: 4.783750528586474 and parameters: {'seq_length': 7, 'hidden_size': 64, 'num_layers': 3, 'dropout_rate': 0.32511400940094354, 'learning_rate': 0.00015189564099964055, 'batch_size': 32}. Best is trial 3 with value: 3.8827161232348137.

Best trial: 3. Best value: 3.88272:  22%|██▏       | 11/50 [02:34<11:42, 18.00s/it]

[I 2026-11-01 20:24:32,884] Trial 10 finished with value: 4.183888440677362 and parameters: {'seq_length': 5, 'hidden_size': 32, 'num_layers': 2, 'dropout_rate': 0.49097326777959804, 'learning_rate': 0.0026038747704701833, 'batch_size': 64}. Best is trial 3 with value: 3.8827161232348137.

Best trial: 3. Best value: 3.88272:  24%|██▍       | 12/50 [02:45<10:02, 15.86s/it]

[I 2026-11-01 20:24:43,859] Trial 11 finished with value: 4.1014973003476305 and parameters: {'seq_length': 10, 'hidden_size': 128, 'num_layers': 1, 'dropout_rate': 0.3913981845941217, 'learning_rate': 0.0013028638904848198, 'batch_size': 64}. Best is trial 3 with value: 3.8827161232348137.

Best trial: 3. Best value: 3.88272:  26%|██▌       | 13/50 [02:59<09:16, 15.05s/it]

[I 2026-11-01 20:24:57,026] Trial 12 finished with value: 4.2567306645166365 and parameters: {'seq_length': 9, 'hidden_size': 128, 'num_layers': 2, 'dropout_rate': 0.39907690583539346, 'learning_rate': 0.00033888122148310375, 'batch_size': 64}. Best is trial 3 with value: 3.8827161232348137.

Best trial: 3. Best value: 3.88272:  28%|██▊       | 14/50 [03:11<08:34, 14.30s/it]

[I 2026-11-01 20:25:09,611] Trial 13 finished with value: 4.186503765271923 and parameters: {'seq_length': 5, 'hidden_size': 128, 'num_layers': 2, 'dropout_rate': 0.24805582979225743, 'learning_rate': 0.009567401209043657, 'batch_size': 64}. Best is trial 3 with value: 3.8827161232348137.

Best trial: 3. Best value: 3.88272:  30%|███       | 15/50 [03:23<07:54, 13.57s/it]

[I 2026-11-01 20:25:21,468] Trial 14 finished with value: 4.076029190193635 and parameters: {'seq_length': 9, 'hidden_size': 32, 'num_layers': 1, 'dropout_rate': 0.38135291767299295, 'learning_rate': 0.0018394581892265706, 'batch_size': 64}. Best is trial 3 with value: 3.8827161232348137.

Best trial: 3. Best value: 3.88272:  32%|███▏      | 16/50 [03:34<07:14, 12.79s/it]

[I 2026-11-01 20:25:32,465] Trial 15 finished with value: 4.188752182790399 and parameters: {'seq_length': 12, 'hidden_size': 128, 'num_layers': 1, 'dropout_rate': 0.4403488505281253, 'learning_rate': 0.00031852423016093457, 'batch_size': 64}. Best is trial 3 with value: 3.8827161232348137.

Best trial: 3. Best value: 3.88272:  34%|███▍      | 17/50 [03:46<06:54, 12.56s/it]

[I 2026-11-01 20:25:44,491] Trial 16 finished with value: 3.9452338638521356 and parameters: {'seq_length': 6, 'hidden_size': 32, 'num_layers': 2, 'dropout_rate': 0.4898452808907783, 'learning_rate': 0.003336267784625113, 'batch_size': 64}. Best is trial 3 with value: 3.8827161232348137.

Best trial: 3. Best value: 3.88272:  36%|███▌      | 18/50 [03:56<06:17, 11.79s/it]

[I 2026-11-01 20:25:54,484] Trial 17 finished with value: 4.093847866474331 and parameters: {'seq_length': 6, 'hidden_size': 32, 'num_layers': 2, 'dropout_rate': 0.48515186374563213, 'learning_rate': 0.004246920624898599, 'batch_size': 64}. Best is trial 3 with value: 3.8827161232348137.

c:\Users\ardel\.conda\envs\pytorch_gpu_env\lib\site-packages\torch\nn\modules\loss.py:626: UserWarning: Using a target size (torch.Size([1])) that is different to the input size (torch.Size([])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
Best trial: 3. Best value: 3.88272:  38%|███▊      | 19/50 [04:02<05:09,  9.98s/it]

[I 2026-11-01 20:26:00,237] Trial 18 finished with value: 4.039531726624683 and parameters: {'seq_length': 4, 'hidden_size': 32, 'num_layers': 2, 'dropout_rate': 0.4983298518329888, 'learning_rate': 0.008523114810828855, 'batch_size': 128}. Best is trial 3 with value: 3.8827161232348137.

Best trial: 3. Best value: 3.88272:  40%|████      | 20/50 [04:23<06:42, 13.43s/it]

[I 2026-11-01 20:26:21,710] Trial 19 finished with value: 3.9992675922221244 and parameters: {'seq_length': 6, 'hidden_size': 32, 'num_layers': 2, 'dropout_rate': 0.42507136828199454, 'learning_rate': 0.0034797227616878354, 'batch_size': 32}. Best is trial 3 with value: 3.8827161232348137.

c:\Users\ardel\.conda\envs\pytorch_gpu_env\lib\site-packages\torch\nn\modules\loss.py:626: UserWarning: Using a target size (torch.Size([1])) that is different to the input size (torch.Size([])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
Best trial: 3. Best value: 3.88272:  42%|████▏     | 21/50 [04:36<06:22, 13.18s/it]

[I 2026-11-01 20:26:34,302] Trial 20 finished with value: 4.059739968066143 and parameters: {'seq_length': 4, 'hidden_size': 32, 'num_layers': 2, 'dropout_rate': 0.24085811652655453, 'learning_rate': 0.0019059504614837256, 'batch_size': 64}. Best is trial 3 with value: 3.8827161232348137.

Best trial: 21. Best value: 3.78793:  44%|████▍     | 22/50 [04:47<05:49, 12.48s/it]

[I 2026-11-01 20:26:45,163] Trial 21 finished with value: 3.7879254614462794 and parameters: {'seq_length': 8, 'hidden_size': 64, 'num_layers': 1, 'dropout_rate': 0.3593153539192411, 'learning_rate': 0.006263832142301876, 'batch_size': 64}. Best is trial 21 with value: 3.7879254614462794.

Best trial: 21. Best value: 3.78793:  46%|████▌     | 23/50 [04:57<05:16, 11.72s/it]

[I 2026-11-01 20:26:55,107] Trial 22 finished with value: 4.044116098904664 and parameters: {'seq_length': 8, 'hidden_size': 64, 'num_layers': 2, 'dropout_rate': 0.4633820111578129, 'learning_rate': 0.0061702576288731785, 'batch_size': 64}. Best is trial 21 with value: 3.7879254614462794.

Best trial: 23. Best value: 3.66435:  48%|████▊     | 24/50 [05:07<04:57, 11.42s/it]

[I 2026-11-01 20:27:05,842] Trial 23 finished with value: 3.664345555390218 and parameters: {'seq_length': 6, 'hidden_size': 64, 'num_layers': 1, 'dropout_rate': 0.4077539707139816, 'learning_rate': 0.004607754398713653, 'batch_size': 64}. Best is trial 23 with value: 3.664345555390218.

c:\Users\ardel\.conda\envs\pytorch_gpu_env\lib\site-packages\torch\nn\modules\loss.py:626: UserWarning: Using a target size (torch.Size([1])) that is different to the input size (torch.Size([])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
Best trial: 23. Best value: 3.66435:  50%|█████     | 25/50 [05:16<04:25, 10.62s/it]

[I 2026-11-01 20:27:14,576] Trial 24 finished with value: 3.932062677387118 and parameters: {'seq_length': 4, 'hidden_size': 64, 'num_layers': 1, 'dropout_rate': 0.35983517203682325, 'learning_rate': 0.009875460358679073, 'batch_size': 64}. Best is trial 23 with value: 3.664345555390218.

Best trial: 23. Best value: 3.66435:  52%|█████▏    | 26/50 [05:25<04:00, 10.01s/it]

[I 2026-11-01 20:27:23,157] Trial 25 finished with value: 3.7389182496548625 and parameters: {'seq_length': 7, 'hidden_size': 64, 'num_layers': 1, 'dropout_rate': 0.4122516784656568, 'learning_rate': 0.005039239501728477, 'batch_size': 64}. Best is trial 23 with value: 3.664345555390218.

Best trial: 23. Best value: 3.66435:  54%|█████▍    | 27/50 [05:33<03:41,  9.61s/it]

[I 2026-11-01 20:27:31,851] Trial 26 finished with value: 3.8786148996451786 and parameters: {'seq_length': 7, 'hidden_size': 64, 'num_layers': 1, 'dropout_rate': 0.4078319726435291, 'learning_rate': 0.004394872471208464, 'batch_size': 64}. Best is trial 23 with value: 3.664345555390218.

Best trial: 23. Best value: 3.66435:  56%|█████▌    | 28/50 [05:42<03:25,  9.33s/it]

[I 2026-11-01 20:27:40,506] Trial 27 finished with value: 4.049833288402415 and parameters: {'seq_length': 8, 'hidden_size': 64, 'num_layers': 1, 'dropout_rate': 0.35994379433806717, 'learning_rate': 0.002177497685957472, 'batch_size': 64}. Best is trial 23 with value: 3.664345555390218.

Best trial: 23. Best value: 3.66435:  58%|█████▊    | 29/50 [05:47<02:48,  8.02s/it]

[I 2026-11-01 20:27:45,466] Trial 28 finished with value: 4.053563256544407 and parameters: {'seq_length': 9, 'hidden_size': 64, 'num_layers': 1, 'dropout_rate': 0.26433402454978455, 'learning_rate': 0.004751703106545931, 'batch_size': 128}. Best is trial 23 with value: 3.664345555390218.

Best trial: 23. Best value: 3.66435:  60%|██████    | 30/50 [06:03<03:27, 10.39s/it]

[I 2026-11-01 20:28:01,397] Trial 29 finished with value: 3.9497107731271113 and parameters: {'seq_length': 7, 'hidden_size': 64, 'num_layers': 1, 'dropout_rate': 0.19116035741615262, 'learning_rate': 0.001630841947305571, 'batch_size': 32}. Best is trial 23 with value: 3.664345555390218.

Best trial: 23. Best value: 3.66435:  62%|██████▏   | 31/50 [06:08<02:46,  8.75s/it]

[I 2026-11-01 20:28:06,310] Trial 30 finished with value: 3.700532487752172 and parameters: {'seq_length': 6, 'hidden_size': 64, 'num_layers': 1, 'dropout_rate': 0.4205579879846798, 'learning_rate': 0.0067447837000955, 'batch_size': 128}. Best is trial 23 with value: 3.664345555390218.

Best trial: 23. Best value: 3.66435:  64%|██████▍   | 32/50 [06:13<02:17,  7.62s/it]

[I 2026-11-01 20:28:11,286] Trial 31 finished with value: 3.7863970253502224 and parameters: {'seq_length': 6, 'hidden_size': 64, 'num_layers': 1, 'dropout_rate': 0.419959204335092, 'learning_rate': 0.007160046169309641, 'batch_size': 128}. Best is trial 23 with value: 3.664345555390218.

Best trial: 23. Best value: 3.66435:  66%|██████▌   | 33/50 [06:18<01:55,  6.81s/it]

[I 2026-11-01 20:28:16,223] Trial 32 finished with value: 4.212459099620148 and parameters: {'seq_length': 6, 'hidden_size': 64, 'num_layers': 1, 'dropout_rate': 0.4202015473510386, 'learning_rate': 0.003717106126428681, 'batch_size': 128}. Best is trial 23 with value: 3.664345555390218.

Best trial: 23. Best value: 3.66435:  68%|██████▊   | 34/50 [06:23<01:39,  6.24s/it]

[I 2026-11-01 20:28:21,138] Trial 33 finished with value: 3.9559036729099986 and parameters: {'seq_length': 7, 'hidden_size': 64, 'num_layers': 1, 'dropout_rate': 0.38179391583461886, 'learning_rate': 0.006479592122343679, 'batch_size': 128}. Best is trial 23 with value: 3.664345555390218.

Best trial: 23. Best value: 3.66435:  70%|███████   | 35/50 [06:28<01:27,  5.85s/it]

[I 2026-11-01 20:28:26,057] Trial 34 finished with value: 4.050996627379449 and parameters: {'seq_length': 5, 'hidden_size': 16, 'num_layers': 1, 'dropout_rate': 0.4252546533880083, 'learning_rate': 0.007267512155767398, 'batch_size': 128}. Best is trial 23 with value: 3.664345555390218.

Best trial: 23. Best value: 3.66435:  72%|███████▏  | 36/50 [06:33<01:18,  5.58s/it]

[I 2026-11-01 20:28:31,015] Trial 35 finished with value: 3.8266957587302213 and parameters: {'seq_length': 6, 'hidden_size': 64, 'num_layers': 1, 'dropout_rate': 0.3290188521619581, 'learning_rate': 0.004786221336189853, 'batch_size': 128}. Best is trial 23 with value: 3.664345555390218.

Best trial: 23. Best value: 3.66435:  74%|███████▍  | 37/50 [06:38<01:10,  5.39s/it]

[I 2026-11-01 20:28:35,976] Trial 36 finished with value: 3.855266484200145 and parameters: {'seq_length': 7, 'hidden_size': 64, 'num_layers': 1, 'dropout_rate': 0.455373226916295, 'learning_rate': 0.002738364573966067, 'batch_size': 128}. Best is trial 23 with value: 3.664345555390218.

Best trial: 23. Best value: 3.66435:  76%|███████▌  | 38/50 [06:42<01:02,  5.24s/it]

[I 2026-11-01 20:28:40,844] Trial 37 finished with value: 3.81483418450183 and parameters: {'seq_length': 5, 'hidden_size': 64, 'num_layers': 1, 'dropout_rate': 0.4675216222239578, 'learning_rate': 0.007550722378235565, 'batch_size': 128}. Best is trial 23 with value: 3.664345555390218.

Best trial: 23. Best value: 3.66435:  78%|███████▊  | 39/50 [06:47<00:56,  5.14s/it]

[I 2026-11-01 20:28:45,757] Trial 38 finished with value: 22.270453483029982 and parameters: {'seq_length': 6, 'hidden_size': 64, 'num_layers': 1, 'dropout_rate': 0.4301596642539807, 'learning_rate': 0.00010978085161331753, 'batch_size': 128}. Best is trial 23 with value: 3.664345555390218.

Best trial: 23. Best value: 3.66435:  80%|████████  | 40/50 [06:52<00:50,  5.07s/it]

[I 2026-11-01 20:28:50,668] Trial 39 finished with value: 4.000237231183729 and parameters: {'seq_length': 5, 'hidden_size': 16, 'num_layers': 1, 'dropout_rate': 0.31181033910583467, 'learning_rate': 0.00619163481176403, 'batch_size': 128}. Best is trial 23 with value: 3.664345555390218.

Best trial: 23. Best value: 3.66435:  82%|████████▏ | 41/50 [06:57<00:45,  5.01s/it]

[I 2026-11-01 20:28:55,534] Trial 40 finished with value: 3.7570151921427883 and parameters: {'seq_length': 6, 'hidden_size': 64, 'num_layers': 1, 'dropout_rate': 0.10548346651014642, 'learning_rate': 0.005086782369166238, 'batch_size': 128}. Best is trial 23 with value: 3.664345555390218.

Best trial: 23. Best value: 3.66435:  84%|████████▍ | 42/50 [07:02<00:39,  4.97s/it]

[I 2026-11-01 20:29:00,428] Trial 41 finished with value: 3.7293838575699025 and parameters: {'seq_length': 6, 'hidden_size': 64, 'num_layers': 1, 'dropout_rate': 0.10543521881100913, 'learning_rate': 0.005187041228542715, 'batch_size': 128}. Best is trial 23 with value: 3.664345555390218.

Best trial: 23. Best value: 3.66435:  86%|████████▌ | 43/50 [07:07<00:34,  4.97s/it]

[I 2026-11-01 20:29:05,380] Trial 42 finished with value: 3.983587982042728 and parameters: {'seq_length': 7, 'hidden_size': 64, 'num_layers': 1, 'dropout_rate': 0.11507382379942499, 'learning_rate': 0.0049792910751673275, 'batch_size': 128}. Best is trial 23 with value: 3.664345555390218.

Best trial: 23. Best value: 3.66435:  88%|████████▊ | 44/50 [07:12<00:30,  5.12s/it]

[I 2026-11-01 20:29:10,865] Trial 43 finished with value: 3.866159634583984 and parameters: {'seq_length': 7, 'hidden_size': 64, 'num_layers': 1, 'dropout_rate': 0.1436772081330678, 'learning_rate': 0.003225028963294133, 'batch_size': 128}. Best is trial 23 with value: 3.664345555390218.

Best trial: 23. Best value: 3.66435:  90%|█████████ | 45/50 [07:20<00:29,  5.89s/it]

[I 2026-11-01 20:29:18,554] Trial 44 finished with value: 4.133390647419355 and parameters: {'seq_length': 5, 'hidden_size': 64, 'num_layers': 3, 'dropout_rate': 0.17099552138452384, 'learning_rate': 0.0024659530091305213, 'batch_size': 128}. Best is trial 23 with value: 3.664345555390218.

Best trial: 23. Best value: 3.66435:  92%|█████████▏| 46/50 [07:36<00:35,  8.88s/it]

[I 2026-11-01 20:29:34,395] Trial 45 finished with value: 3.859599544928802 and parameters: {'seq_length': 6, 'hidden_size': 16, 'num_layers': 1, 'dropout_rate': 0.21166583490830257, 'learning_rate': 0.00384585845321035, 'batch_size': 32}. Best is trial 23 with value: 3.664345555390218.

Best trial: 23. Best value: 3.66435:  94%|█████████▍| 47/50 [07:42<00:24,  8.04s/it]

[I 2026-11-01 20:29:40,496] Trial 46 finished with value: 3.9363091254057023 and parameters: {'seq_length': 8, 'hidden_size': 64, 'num_layers': 1, 'dropout_rate': 0.10626582754497028, 'learning_rate': 0.005467704428728892, 'batch_size': 128}. Best is trial 23 with value: 3.664345555390218.

Best trial: 23. Best value: 3.66435:  96%|█████████▌| 48/50 [07:48<00:14,  7.29s/it]

[I 2026-11-01 20:29:46,022] Trial 47 finished with value: 6.157661421431436 and parameters: {'seq_length': 5, 'hidden_size': 64, 'num_layers': 1, 'dropout_rate': 0.27150395895631263, 'learning_rate': 0.0005022404905814929, 'batch_size': 128}. Best is trial 23 with value: 3.664345555390218.

Best trial: 23. Best value: 3.66435:  98%|█████████▊| 49/50 [08:05<00:10, 10.18s/it]

[I 2026-11-01 20:30:02,949] Trial 48 finished with value: 3.868141851825745 and parameters: {'seq_length': 6, 'hidden_size': 64, 'num_layers': 1, 'dropout_rate': 0.14658151654837165, 'learning_rate': 0.0012302321707430809, 'batch_size': 32}. Best is trial 23 with value: 3.664345555390218.

Best trial: 23. Best value: 3.66435: 100%|██████████| 50/50 [08:10<00:00,  9.80s/it]

[I 2026-11-01 20:30:07,940] Trial 49 finished with value: 4.0510708438418925 and parameters: {'seq_length': 3, 'hidden_size': 64, 'num_layers': 1, 'dropout_rate': 0.13640822089910978, 'learning_rate': 0.003066111779504549, 'batch_size': 128}. Best is trial 23 with value: 3.664345555390218.

=== OPTUNA LSTM TUNING COMPLETE ===
Best Validation MAE: 3.6643%
Best Parameters: {'seq_length': 6, 'hidden_size': 64, 'num_layers': 1, 'dropout_rate': 0.4077539707139816, 'learning_rate': 0.004607754398713653, 'batch_size': 64}

# Save Model

In [27]:
OPTIMAL_SEQ_LENGTH = 6
X_tr_final, y_tr_final = create_sequences(X_train_scaled, y_train_raw, OPTIMAL_SEQ_LENGTH)
X_te_final, y_te_final = create_sequences(X_test_scaled, y_test_raw, OPTIMAL_SEQ_LENGTH)

train_dataset_final = TensorDataset(torch.tensor(X_tr_final, dtype=torch.float32), 
                                    torch.tensor(y_tr_final, dtype=torch.float32))
# Using the best batch_size of 64
train_loader_final = DataLoader(train_dataset_final, batch_size=64, shuffle=False)

In [28]:
final_model = SmartBinLSTM(
    input_size=len(features), 
    hidden_size=64,           # Best hidden_size
    num_layers=1,             # Best num_layers
    output_size=1, 
    dropout_rate=0.4077       # Best dropout_rate
).to(device)

criterion = nn.MSELoss()
optimizer = torch.optim.Adam(final_model.parameters(), lr=0.0046)

In [29]:
EPOCHS = 50
print("Training Final Golden Model on GPU...")
final_model.train()
for epoch in range(EPOCHS):
    for X_batch, y_batch in train_loader_final:
        X_batch, y_batch = X_batch.to(device), y_batch.to(device)
        optimizer.zero_grad()
        preds = final_model(X_batch)
        loss = criterion(preds, y_batch)
        loss.backward()
        optimizer.step()

# 4. Safely Export the Model Weights
save_dir = 'model'
os.makedirs(save_dir, exist_ok=True)
model_path = os.path.join(save_dir, 'lstm_smartbin_16days_final.pth')

# We save the state_dict (the actual learned weights), not the entire class object
torch.save(final_model.state_dict(), model_path)
print(f"\nSUCCESS: Model weights safely locked and exported to -> {model_path}")

Training Final Golden Model on GPU...

SUCCESS: Model weights safely locked and exported to -> model\lstm_smartbin_16days_final.pth